language: php

# list the PHP versions to test against
php:
# alaised to the recent 7.x version
- '7.0'
# aliased to the recent 5.6.x version
- '5.6'
# aliased to the recent 5.5.x version
- '5.5'
# aliased to the recent 5.4.x version
- '5.4'
# aliased to 5.3.29
- '5.3'
# aliased to 5.2.17
- '5.2'
# aliased to the recent hhvm version
- hhvm
# aliased to the recent nightly version
- nightly
